### ISSUE TITLE
Modules dependency resolution

### ISSUE THREAD

**Issue by bre1470** [highcharts/highcharts-assembler#10]
Currently we have no link specifying dependencies between distributed bundles. This means that our AMD patterns are incomplete, as it is not possible to require a single module and get all of its dependencies automatically. See https://github.com/highcharts/highcharts/issues/8890

We propose a fix:
- [x] new tags in doclet in `js/masters/`:  `@module` `@requires`
- [x] assembler has to lookup all `@module` names in `js/masters` which are referenced by `@requires` and can exclude dependent parts
- [x] extended define like `define( _module_name_ , [ _requires_name_ ], () => {})`
- [x] make sure that all `@module` names start with `highcharts` to be unique in users use cases
- [x] remove new tags from bundle result
- [x] change the UMD pattern so that factory gets an Highcharts property (in all conditional statements), that can be used like this `import { Highcharts } from 'highcharts/modules/offline-exporting';`

**Comment by jon-a-nygaard** [comment]
# Updates to the AMD pattern
As of [v1.3.1](https://github.com/highcharts/highcharts-assembler/releases/tag/v1.3.1) the bundler supports adding module name and dependencies to the AMD define.

## Module name
The module name can be set as in the userOptions as following:
```javascript
build({
  moduleName: 'module-name'
})
```
If it is not provided in the userOptions the assembler will use the `@module` tag if found in the entry file.
```javascript
/**
 * My module
 * @module module-name
 */
```

## Module dependencies
The module dependencies can be set in the userOptions as following:
```javascript
build({
  requires: ['highcharts', 'highcharts/modules/exporting']
})
```
If it is not provided in the userOptions the assembler will use the `@requires` tags if found in the entry file.
```javascript
/**
 * This module has a dependency on `highcharts` and `highcharts/modules/exporting`
 * @requires highcharts
 * @requires highcharts/modules/exporting
 */
```
If dependencies are provided, the assembler will assume that the first dependency is the Highcharts instance. It will then run the factory function on the instance, and afterwards attach the updated instance to the returned factory function as a property named Highcharts.
```javascript
define(..., function (Highcharts) {
  factory(Highcharts);
  factory.Highcharts = Highcharts;
  return factory;
});
```

**Comment by bre1470** [comment]
@jon-a-nygaard Can you check, if some of the open issue points can be marked solved? I believe `remove new tags from bundle result` was for example done.

**Comment by jon-a-nygaard** [comment]
@bre1470 Yes, I believe the criteria in this issue is met and that we can close the issue.
