### ISSUE TITLE
What are the 'core' files referenced in the "Download Builder (experimental)"

### ISSUE THREAD

**Issue by NathanKleekamp** [highcharts/highcharts-assembler#4]
On the Highcharts Download page, there is an "experimental" Download Builder that references a "core" library. What files in the `highcharts/js` directory does that "core" library map to?

**Comment by jon-a-nygaard** [comment]
Hi @NathanKleekamp,

Apologies for the very late reply.

In case you are still wondering, the "core" feature in the download builder is currently mapped to the following files:
- `/parts/Axis.js`
- `/parts/Chart.js`
- `/parts/Legend.js`
- `/parts/Point.js`
- `/parts/Series.js`

Keep in mind that this may change as the definition of the "core" feature in download builder may change, or the structure and naming of the code files may change.

Best regards
Jon
